In [3]:
x = "Python"
print(x * 3)


PythonPythonPython


In [6]:
add = lambda x, y: x + y
print(add(3, 5))  

8


In [8]:
x = 10
if x > 5:
    print("Greater than 5")
elif x == 5:
    print("Equal to 5")
else:
    print("Less than 5")


Greater than 5


In [10]:
for i in range(2, 11, 2):
    print(i)

2
4
6
8
10


In [12]:
numbers = [1, 2, 2, 3, 4, 4, 5]
unique_numbers = list(set(numbers))
print(unique_numbers)


[1, 2, 3, 4, 5]


##  Write a program to create a list of squares from 1 to 5 using list comprehension.

In [16]:
squares = [x**2 for x in range(1, 6)]
print(squares)

[1, 4, 9, 16, 25]


## How do you define a class and create an object in Python?

In [19]:
class Dog:
    def __init__(self,name):
        self.name = name

    def bark(self):
        print(f"{self.name} says woof!")

Dog1 = Dog("Buddy")
Dog1.bark()


Buddy says woof!


## Q: How do you create a NumPy array of zeros with shape (3, 3)?

In [26]:
import numpy as np
array = np.zeros((3, 3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## How do you create a DataFrame from a dictionary?

In [29]:
import pandas as pd
data = {'Name': ['Aarti', 'John'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Aarti   25
1   John   30
