## Assignment-7

## 1)Create an array of all even integers from 10-50.

In [3]:
import numpy as np

even_array = np.arange(10,51,2)
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


## 2)Create an array of 20 linearly spaced points between 0 and 1.

In [5]:
linear_array = np.linspace(0,1,20)
print(linear_array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## 3)Write a NumPy program to compute the cross product of two given vectors.

In [7]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
cross_product = np.cross(vector1, vector2)
print(cross_product)

[-3  6 -3]


## 4)Write a NumPy program to generate six random integers between 10 and 30.

In [40]:
import numpy as np

# Generate six random integers between 10 and 30
random_integers = np.random.randint(10, 31,size = 10)

print("Random integers between 10 and 30:", random_integers)


Random integers between 10 and 30: [13 29 16 16 29 18 24 18 27 11]


## 5)Write a python program to add two numpy arrays.

In [45]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Method 1: Using numpy.add()
sum_array1 = np.add(array1, array2)
sum_array1 

array([11, 22, 33, 44, 55])

## 6)Write a python program to demonstrate indexing in NumPy array.

In [16]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access elements using index
print("Element at index (0, 0):", arr[0, 0])  # Access element at row 0, column 0
print("Element at index (1, 2):", arr[1, 2])  # Access element at row 1, column 2

# Accessing entire row and column
print("Row at index 1:", arr[1, :])  # Access entire row at index 1
print("Column at index 2:", arr[:, 2])  # Access entire column at index 2

# Accessing a sub-array using slicing
print("Sub-array from row 1 to 2 and column 0 to 2:\n", arr[1:3, 0:2])


Element at index (0, 0): 1
Element at index (1, 2): 6
Row at index 1: [4 5 6]
Column at index 2: [3 6 9]
Sub-array from row 1 to 2 and column 0 to 2:
 [[4 5]
 [7 8]]


## Create a data frame using `df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) then add a new column to it.

In [7]:
import pandas as pd
from numpy import random


df = pd.DataFrame(random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())

# Adding a new column to the DataFrame
df['NewCol'] = [1, 2, 3, 4, 5]  # Adding a simple column with values 1, 2, 3, 4, 5

# Display the DataFrame
print(df)


          W         X         Y         Z  NewCol
A -0.360035  1.737295 -1.394694 -0.872255       1
B -1.076486 -0.501382  0.492693 -0.398306       2
C  0.540123 -0.177771  0.804708  0.925494       3
D  2.117914 -0.132590 -0.711446 -0.756774       4
E  1.996606 -0.804803  0.835839  0.338232       5


## 2)Develop a dataframe for
## data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'], 'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'], 'Sales':[200,120,340,124,243,350]}.

## Then group the data using company column.

In [10]:
import pandas as pd

# Create the DataFrame
data = {'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
        'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Sales': [200, 120, 340, 124, 243, 350]}

df = pd.DataFrame(data)

# Group by the 'Company' column
grouped = df.groupby('Company')

# Display the groups
for company, group in grouped:
    print(f"Company: {company}")
    print(group, "\n")


Company: FB
  Company Person  Sales
4      FB   Carl    243
5      FB  Sarah    350 

Company: GOOG
  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120 

Company: MSFT
  Company   Person  Sales
2    MSFT      Amy    340
3    MSFT  Vanessa    124 



## 3)Write a Pandas program to remove repetitive characters from the specified column of a given DataFrame.

In [13]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['neha', 'vaishali', 'rohit', 'divya'],
        'Text': ['aabbcc', 'xxxyyy', 'aaabbbccc', 'ppqqrrss']}

df = pd.DataFrame(data)

# Remove consecutive repetitive characters in the 'Text' column
df['Text'] = df['Text'].str.replace(r'(.)\1+', r'\1', regex=True)

# Display the updated DataFrame
print(df)


       Name  Text
0      neha   abc
1  vaishali    xy
2     rohit   abc
3     divya  pqrs


## 4)Write a Pandas program to create a Pivot table and find the total sale amount region wise, manager wise, sales man wise.

In [19]:
import pandas as pd

# Sample data: Sales records
data = {
    'Region': ['North', 'South', 'North', 'East', 'West', 'South', 'West', 'North'],
    'Manager': ['neha', 'javid', 'sushant', 'anjali', 'nikita', 'aarti', 'shweta', 'rohan'],
    'Salesman': ['samir', 'sam', 'nisha', 'raj', 'usha', 'mitali', 'adi', 'vedika'],
    'Sale_Amount': [500, 700, 800, 600, 900, 650, 950, 750]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create a pivot table to sum the sale amounts based on Region, Manager, and Salesman
pivot_table = pd.pivot_table(df, values='Sale_Amount', index=['Region', 'Manager', 'Salesman'], aggfunc='sum')

# Display the pivot table
print(pivot_table)


                         Sale_Amount
Region Manager Salesman             
East   anjali  raj               600
North  neha    samir             500
       rohan   vedika            750
       sushant nisha             800
South  aarti   mitali            650
       javid   sam               700
West   nikita  usha              900
       shweta  adi               950


## 5)Write a python program to create a data frame from 2 dictionaries.

In [23]:
import pandas as pd

# Define two dictionaries
data1 = {
    'Name': ['neha', 'aarti', 'anjali'],
    'Age': [24, 27, 22],
    'City': ['pune', 'mumbai', 'delhi']
}

data2 = {
    'Name': ['nikita', 'sam', 'samir'],
    'Age': [29, 31, 25],
    'City': ['satara', 'kolhapur', 'pune']
}

# Create DataFrames from the dictionaries
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)


df = pd.concat([df1, df2], ignore_index=True)


print(df)


     Name  Age      City
0    neha   24      pune
1   aarti   27    mumbai
2  anjali   22     delhi
3  nikita   29    satara
4     sam   31  kolhapur
5   samir   25      pune


In [30]:
import pandas as pd

# Create an initial employee register (empty DataFrame)
columns = ['EmpID', 'EmpName', 'EmpSalary', 'EmpDesignation']
employee_register = pd.DataFrame(columns=columns)

# Add employee details using pd.concat()
new_employee1 = pd.DataFrame([{'EmpID': 101, 'EmpName': 'neha', 'EmpSalary': 50000, 'EmpDesignation': 'Manager'}])
new_employee2 = pd.DataFrame([{'EmpID': 102, 'EmpName': 'nisha', 'EmpSalary': 45000, 'EmpDesignation': 'Developer'}])
new_employee3 = pd.DataFrame([{'EmpID': 103, 'EmpName': 'vedika', 'EmpSalary': 40000, 'EmpDesignation': 'Tester'}])

# Concatenate the new records to the employee register
employee_register = pd.concat([employee_register, new_employee1, new_employee2, new_employee3], ignore_index=True)

# Set "EmpID" as the index
employee_register.set_index('EmpID', inplace=True)

# Display the employee register
print(employee_register)


      EmpName EmpSalary EmpDesignation
EmpID                                 
101      neha     50000        Manager
102     nisha     45000      Developer
103    vedika     40000         Tester


## Graded Assignments

## 1) NumPy Program to Calculate the Difference Between the Maximum and Minimum Values of a Given Array Along the Second Axis

In [38]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 5, 3], [7, 2, 6], [4, 8, 9]])

# Find the maximum values along the second axis (columns)
max_values = np.max(arr, axis=1)

# Find the minimum values along the second axis (columns)
min_values = np.min(arr, axis=1)

# Calculate the difference between max and min along the second axis (columns)
difference = max_values - min_values

print("Original Array:\n", arr)
print("\nDifference between max and min values along the second axis:\n", difference)


Original Array:
 [[1 5 3]
 [7 2 6]
 [4 8 9]]

Difference between max and min values along the second axis:
 [4 5 5]


## 2) Pandas Program to Get a Time Series with the Last Working Days of Each Month for a Specific Year

In [47]:
import pandas as pd

# Specify the year
year = 2024


last_working_days = pd.date_range(f'{year}-01-01', f'{year}-12-31', freq='BM')

# Display the last working days of each month
print("Last Working Days of Each Month in", year, ":\n", last_working_days)


Last Working Days of Each Month in 2024 :
 DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-29', '2024-04-30',
               '2024-05-31', '2024-06-28', '2024-07-31', '2024-08-30',
               '2024-09-30', '2024-10-31', '2024-11-29', '2024-12-31'],
              dtype='datetime64[ns]', freq='BME')


C:\Users\Aarti Salunkhe\AppData\Local\Temp\ipykernel_33516\3120775483.py:7: FutureWarning: 'BM' is deprecated and will be removed in a future version, please use 'BME' instead.
  last_working_days = pd.date_range(f'{year}-01-01', f'{year}-12-31', freq='BM')
