In [1]:
import numpy as np

In [2]:
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [3]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
a = np.array(my_list)

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)    # ndarray is number dimension array

numpy.ndarray

In [7]:
a.ndim  # number of dimensions in the array

1

In [8]:
a.size  # size of an array is the no. of items 

5

In [9]:
a.shape # shape of array   #no of rows and column (rows,column)

(5,)

In [10]:
a.dtype

dtype('int32')

#### Arrays can be of n dimensions.

In [12]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [13]:
b = np.array(my_matrix)  # generates a 2-d array

In [14]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
type(b)

numpy.ndarray

In [16]:
b.dtype

dtype('int32')

In [17]:
b.shape

(3, 4)

In [18]:
b.size

12

In [19]:
# Array summary
print('The Dimension of array',b.ndim)

The Dimension of array 2


In [20]:
b.ndim


2

### 1 d array

In [22]:
arr2 = np.array([1,2,4,6,8])
print(arr2)
print(arr2.ndim)

[1 2 4 6 8]
1


### 2 d array

In [24]:
arr3 = np.array([[1,2,4,6,8],[5,3,6,5,1]])
print(arr3)
print(arr3.ndim)


[[1 2 4 6 8]
 [5 3 6 5 1]]
2


### 3 d array

In [26]:
arr4 = np.array([[[1,2,4,6,8] ,[5,3,6,5,1] ,[2,5,6,5,8]]])
print(arr4)
print(arr4.ndim)

[[[1 2 4 6 8]
  [5 3 6 5 1]
  [2 5 6 5 8]]]
3


In [27]:
arr5 = np.array([[[5,6,6],[5,8,9]],[[5,7,8],[9,6,3]]])
arr5

array([[[5, 6, 6],
        [5, 8, 9]],

       [[5, 7, 8],
        [9, 6, 3]]])

In [28]:
arr5.shape

(2, 2, 3)

In [29]:
arr5.ndim

3

In [30]:
a = np.array(45)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,],[5,5,6]])
d = np.array([[[5,6,4],[5,8,9]],[[5,7,8],[9,6,3]]])

In [31]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [32]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [33]:
arr = np.array([1,2,3,4,5])
print(arr[-1])

5


In [34]:
import numpy as np

In [35]:
arr = np.array([1, 2, 3, 4,5], ndmin=5)
print(arr)
print('number of dimension :',arr.ndim )


[[[[[1 2 3 4 5]]]]]
number of dimension : 5


In [36]:
arr1 = np.array([1, 2, 3, 4], ndmin = 5)
print(arr1)
print("number of dimension",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension 5


In [37]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr[1,1])

60


In [38]:
arr1 = ([[10, 20, 30, 40], [50, 60, 70, 80]])
arr1

[[10, 20, 30, 40], [50, 60, 70, 80]]