## Introduction to NumPy
#### NumPy is a Python library created in 2005 that performs numerical calculations. 
#### It is generally used for working with arrays.

#### NumPy also includes a wide range of mathematical functions, 
#### such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.



## What is NumPy Used for?
#### NumPy is an important library generally used for:

#### Machine Learning
#### Data Science
#### Image and Signal Processing
#### Scientific Computing
#### Quantum Computing


## Why Use NumPy?
#### Some of the major reasons why we should use NumPy are:

#### 1. Faster Execution

#### In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.

#### Numpy arrays are optimized for complex mathematical and statistical operations. 
#### Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

#### Here're some of the reasons why NumPy is so fast:

#### Uses specialized data structures called numpy arrays.
#### Created using high-performance languages like C and C++.


## 2. Used with Various Libraries

#### NumPy is heavily used with various libraries like Pandas, Scipy, scikit-learn, etc.

## import numpy as np
#### The code above imports the numpy library in our program as an alias np.

#### After this import statement, we can use NumPy functions and objects by calling them with np.

## NumPy Array Creation
#### An array allows us to store a collection of multiple values in a single data structure.

#### The NumPy array is similar to a list, but with added benefits such as being faster and more memory efficient.

#### Numpy library provides various methods to work with data. To leverage all those features, we first need to create numpy arrays.

#### There are multiple techniques to generate arrays in NumPy, and we will explore each of them below.

### Create Array Using Python List
##### We can create a NumPy array using a Python List. For example,



In [9]:
import numpy as np

In [10]:
# create a list named list1
list1 = [2, 4, 6, 8]

#create a list named list1
array1 = np.array(list1)
print(array1)

[2 4 6 8]


In [11]:
import numpy as np

# create numpy array using a list
array1 = np.array([2,4,6,8,10])
print(array1)

[ 2  4  6  8 10]


### Create an Array Using np.zeros()

#### create an array with 4 elements filled with zeros

In [14]:
array1 = np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [15]:
array1 = np.zeros(4)
array1

array([0., 0., 0., 0.])

In [16]:
#Here, we have created an array named array1 with 4 elements all initialized to 0 using the np.zeros(4) function.

In [17]:
#Note: Similarly we can use np.ones() to create an array filled with values 1.

In [18]:
array1 = np.ones(4)
print(array1)

[1. 1. 1. 1.]


## Create an Array With np.arange()

In [20]:
#The np.arange() function returns an array with values within a specified interval. For example,

In [21]:
# create an array with values from 0 to 4
array1 = np.arange(5)
print("Using np.arange(5):", array1)      

Using np.arange(5): [0 1 2 3 4]


In [22]:
# create an arrays with values from 1 to 8 a step of 2
array2 = np.arange(1,9,2)
print("Using np.arange(1,9,2):", array2)

Using np.arange(1,9,2): [1 3 5 7]


In [23]:
#In the above example, we have created arrays using the np.arange() function.

In [24]:
#np.arange(5) - create an array with 5 elements, where the values range from 0 to 4
#np.arange(1, 9, 2) - create an array with 5 elements, where the values range from 1 to 8 with a step of 2.

## Create an Array With np.random.rand()

In [26]:
#The np.random.rand() function is used to create an array of random numbers.

#Let's see an example to create an array of 5 random numbers,

# generate an array of 5 random numbers

array1 = np.random.rand(5)
print(array1)

[0.94528346 0.01360906 0.12877958 0.21303353 0.79080557]


In [27]:
#In the above example, we have used the np.random.rand() function to create an array array1 with 5 random numbers.

#This code generates a different output each time we run it.

### Create an Empty NumPy Array

In [29]:
import numpy as np

In [30]:
#To create an empty NumPy array, we use the np.empty() function. For example,

In [31]:
import numpy as np

# create an empty array of length 5
array1 = np.empty(5)

print(array1)

[0.94528346 0.01360906 0.12877958 0.21303353 0.79080557]


In [32]:
#Here, we have created an empty array of length 4 using the np.empty() function.

#If we look into the output of the code, we can see the empty array is actually not empty, it has some values in it.

#It is because although we are creating an empty array, NumPy will try to add some value to it.
#The values stored in the array are arbitrary and have no significance.

## NumPy N-D Array Creation
#### NumPy is not restricted to 1-D arrays, it can have arrays of multiple dimensions, also known as N-dimensional arrays or ndarrays.

#### An N-dimensional array refers to the number of dimensions in which the array is organized.

#### An array can have any number of dimensions and each dimension can have any number of elements.

#### For example, a 2D array represents a table with rows and columns, while a 3D array represents a cube with width, height, and depth.

#### There are multiple techniques to create N-d arrays in NumPy, and we will explore each of them below.

## N-D Array Creation From List of Lists

In [35]:
#To create an N-dimensional NumPy array from a Python List,
#we can use the np.array() function and pass the list as an argument.

### Create a 2-D NumPy Array

In [37]:
#Let's create a 2D NumPy array with 2 rows and 4 columns using lists.

In [38]:
import numpy as np

# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [39]:
#In the above example, we first created a 2D list (list of lists) [[1, 2, 3, 4], [5, 6, 7, 8]] with 2 rows and 4 columns.
#We then passed the list to the np.array() function to create a 2D array.

## Create a 3-D NumPy Array

In [41]:
#Let's say we want to create a 3-D NumPy array consisting of two "slices" where each slice has 3 rows and 4 columns.

In [42]:
#Here's how we create our desired 3-D array,

### create a 3D array with 2 "slices", each of 3 rows and 4 columns

In [44]:
array2 = np.array([[[1,2,3,4],[4,5,6,7],[7,8,5,3]] , [[4,6,9,5],[5,6,0,5],[8,5,2,3]]])
print(array2)


[[[1 2 3 4]
  [4 5 6 7]
  [7 8 5 3]]

 [[4 6 9 5]
  [5 6 0 5]
  [8 5 2 3]]]


In [45]:
#Here, we created a 3D list [list of lists of lists] and passed it to the np.array() function. This creates the 3-D array named array2.

In [46]:
#In the 3D list,

#The outermost list contains two elements, which are lists representing the two "slices" of the array.
#Each slice is a 2-D array with 3 rows and 4 columns.
#The innermost lists represent the individual rows of the 2-D arrays.

In [47]:
#Note: In the context of an N-D array, a slice is like a subset of the array that we can take out by selecting a specific range of rows, columns.

## Creating N-d Arrays From Scratch


In [49]:
#We saw how to create N-d NumPy arrays from Python lists. Now we'll see how we can create them from scratch.

#To create multidimensional arrays from scratch we use functions such as
#np.zeros()
#np.arange()
#np.random.rand()


## Create N-D Arrays using np.zeros()

In [51]:
#The np.zeros() function allows us to create N-D arrays filled with all zeros. For example,

In [52]:
# create 2D array with 2 rows and 3 columns filled with zeros
array1 = np.zeros((2,3))
print("2d array:")
print(array1)

2d array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
# create 3D array with dimensions 2x3x4 filled with zeros
array2 = np.zeros((2,3,4))
print("3d array:")
print(array2)

3d array:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


#### In the above example, we have used the np.zeros() function to create a 2-D array and 3-D array filled with zeros respectively.
#### np.zeros((2, 3)) - returns a zero filled 2-D array with 2 rows and 3 columns
#### np.zeros((2, 3, 4)) - returns a zero filled 3-D array with 2 slices, each slice having 3 rows and 4 columns.

In [55]:
## Note: Similarly we can use np.ones() to create an array filled with values 1.

## Create N-D Array with a Specified Value

In [57]:
#In NumPy, we can use the np.full() function to create a multidimensional array with a specified value.

### For example, to create a 2-D array with the value 5, we can do the following:

In [59]:
# Create a 2-D array with elements initialized to 5 
numpy_array = np.full((2,2),5)
print(numpy_array)

[[5 5]
 [5 5]]


In [60]:
#Here, we have used the np.full() function to create a 2-D array where all elements are initialized to 5.

In [61]:
numpy_array1 = np.full((3,2),6)
print(numpy_array1)

[[6 6]
 [6 6]
 [6 6]]


## Creating Arrays With np.random.rand()

### The np.random.rand() function is used to create an array of random numbers.

In [64]:
#Let's see an example to create an array of 5 random numbers,

In [65]:
# create a 2D array of 2 rows and 2 columns of random numbers
array1 = np.random.rand(2, 2)
print(array1)

[[0.06482853 0.11720149]
 [0.56869463 0.81075977]]


In [66]:
# create a 3D array of shape (2, 2, 2) of random numbers
array2= np.random.rand(2,2,2)
print(array2)

[[[0.80457985 0.73288504]
  [0.18438292 0.8441796 ]]

 [[0.05958431 0.70683651]
  [0.151215   0.07229112]]]


In [67]:
#Here,
#np.random.rand(2, 2) - creates a 2D array of 2 rows and 2 columns of random numbers.
#np.random.rand(2, 2, 2) - creates a 3D array with 2 slices, each slice having 2 rows and 2 columns of random numbers.

## Create Empty N-D NumPy Array

### To create an empty N-D NumPy array, we use the np.empty() function. For example,

In [70]:
# create an empty 2D array with 2 rows and 2 columns
array1 = np.empty((2, 2))
print(array1)

[[0.06482853 0.11720149]
 [0.56869463 0.81075977]]


In [71]:
# create an empty 3D array of shape (2, 2, 2) 
array2 = np.empty((2, 2, 2))
print(array2)

[[[0.80457985 0.73288504]
  [0.18438292 0.8441796 ]]

 [[0.05958431 0.70683651]
  [0.151215   0.07229112]]]


In [72]:
#In the above example, we used the np.empty() function to create an empty 2-D array and a 3-D array respectively.

#If we look into the output of the code, we can see the empty array is actually not empty, it has some values in it.

#It is because although we are creating an empty array, NumPy will try to add some value to it.
#The values stored in the array are arbitrary and have no significance value.

## NumPy Data Types
#A data type is a way to specify the type of data that will be stored in an array. For example,

In [74]:
array1 = np.array([2, 4, 6])
#Here, the array1 array contains three integer elements, so the data type is Integer(int64)), by default.

#NumPy provides us with several built-in data types to efficiently represent numerical data.

## NumPy Data Types
#NumPy offers a wider range of numerical data types than what is available in Python. 
#Here's the list of most commonly used numeric data types in NumPy:

In [76]:
#int8, int16, int32, int64 -     signed integer types with different bit sizes
#uint8, uint16, uint32, uint64 - unsigned integer types with different bit sizes
#float32, float64 -             floating-point types with different precision levels
#complex64, complex128 -       complex number types with different precision levels

### Check Data Type of a NumPy Array

In [78]:
import numpy as np

# create an array of integers 
array1 = np.array([2, 4, 6])
# check the data type of array1
print(array1.dtype)

int32


In [79]:
#In the above example, we have used the dtype attribute to check the data type of the array1 array.

#Since array1 is an array of integers, the data type of array1 is inferred as int64 by default.

## Example: Check Data Type of NumPy Array


In [81]:
# create an array of  integers
int_array = np.array([-3, -1, 0, 1])
print(int_array.dtype)

int32


In [82]:
#create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])
print(float_array.dtype)

float64


In [83]:
#create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])
print(complex_array.dtype)

complex128


In [84]:
#Here, we have created types of arrays and checked the default data types of these arrays using the dtype attribute.

#int_array - contains four integer elements whose default data type is int64
#float_array - contains three floating-point numbers whose default data type is float64
#complex_array - contains three complex numbers whose default data type is complex128

## Creating NumPy Arrays With a Defined Data Type
#### In NumPy, we can create an array with a defined data type by passing the dtype parameter while calling the np.array() function. For example,

In [86]:
# create an array of 32-bit integers
array1 = np.array([4,6,5],dtype = int)
print(array1)
print(array1.dtype)

[4 6 5]
int32


In [87]:
#In the above example, we have created a NumPy array named array1 with a defined data type.

#Notice the code,

#np.array([1, 3, 7], dtype='int32')
#Here, inside np.array(), we have passed an array [1, 3, 7] and set the dtype parameter to int32.

#Since we have set the data type of the array to int32, each element of the array is represented as a 32-bit integer.

In [88]:
array2 = np.array([4,5,63.2],dtype = float)
print(array2.dtype)
print(array2)

float64
[ 4.   5.  63.2]


In [89]:
array3 = np.array([4, 5, 63.2],dtype = complex)
print(array3.dtype)
print(array3)

complex128
[ 4. +0.j  5. +0.j 63.2+0.j]


## Example: Creating NumPy Arrays With a Defined Data Type

In [91]:
# create an array of 8-bit integers
array4 = np.array([2, 4, 6], dtype=int)
print(array4)
print(array4.dtype)


[2 4 6]
int32


## NumPy Type Conversion

#### In NumPy, we can convert the data type of an array using the astype() method. For example,



In [94]:
# create an array of integers
int_array = np.array([1, 3, 5, 7])

# convert data type of int_array to float
float_array = int_array.astype(float)

print(int_array,int_array.dtype)
print(float_array,float_array.dtype)

[1 3 5 7] int32
[1. 3. 5. 7.] float64


#### Here, int_array.astype('float') converts the data type of int_array from int64 to float64 using astype().

## NumPy Array Attributes
#In NumPy, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on.

#For example, to get the dimension of an array, we can use the ndim attribute.

#There are numerous attributes available in NumPy, which we'll learn below.

## Common NumPy Attributes
##### Here are some of the commonly used NumPy attributes:

### Attributes	Description
#### ndim	returns number of dimension of the array

#### size	returns number of elements in the array

#### dtype	returns data type of elements in the array

#### shape	returns the size of the array in each dimension.

#### itemsize	returns the size (in bytes) of each elements in the array

#### data	returns the buffer containing actual elements of the array in memory

In [98]:
#To access the Numpy attributes, we use the . notation. For example,
#array1.ndim
#This returns the number of dimensions in array1.

## Numpy Array ndim Attribute

### The ndim attribute returns the number of dimensions in the numpy array. For example,

In [101]:
import numpy as np

# create a 2-D array 
array1 = np.array([[2, 4, 6], [1, 3, 5]])

# check the dimension of array1
print(array1.ndim)
print(array1)

2
[[2 4 6]
 [1 3 5]]


In [102]:
#In this example, array1.ndim returns the number of dimensions present in array1. As array1 is a 2D array, we got 2 as an output.

## NumPy Array size Attribute


### The size attribute returns the total number of elements in the given array.
#Let's see an example.

In [105]:
array2 = np.array([[2, 4, 6], [1, 3, 5]])
print(array2)

# return total number of elements in array1
print(array2.size)

[[2 4 6]
 [1 3 5]]
6


In [106]:
#In this example, array1.size returns the total number of elements in the array1 array, regardless of the number of dimensions.
#Since these are a total of 6 elements in array1, the size attribute returns 6

## NumPy Array shape Attribute


### In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension. For example,


In [109]:
array3 = np.array([[2, 8, 6], [1, 3, 6]])
print(array3)
# return a tuple that gives size of array in each dimension
print(array3.shape)

[[2 8 6]
 [1 3 6]]
(2, 3)


#### Here, array1 is a 2-D array that has 2 rows and 3 columns. So array1.shape returns the tuple (2,3) as an output.

## NumPy Array dtype Attribute

#### We can use the dtype attribute to check the datatype of a NumPy array. For example,


In [113]:
# create an array of floating 
array1 = np.array([6.5, 7.7, 8.1])

# check the data type of array1
print(array1.dtype) 

float64


In [114]:
#In the above example, the dtype attribute returns the data type of array1.
#Since array1 is an array of integers, the data type of array1 is inferred as int64 by default.

## NumPy Array itemsize Attribute

In [116]:
#In NumPy, the itemsize attribute determines size (in bytes) of each element in the array. For example,

In [117]:
import numpy as np

# create a default 1-D array of integers
array5 = np.array([6, 7, 8, 10, 13,85],dtype=np.int64)

# create a 1-D array of 32-bit integers 
array6 = np.array([6, 7, 8, 10, 13,45], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array5.itemsize)  
print(array6.itemsize)  

8
4


In [118]:
#array1 is an array containing 64-bit integers by default, which uses 8 bytes of memory per element.
#So, itemsize returns 8 as the size of each element.
#array2 is an array of 32-bit integers, so each element in this array uses only 4 bytes of memory.
#So, itemsize returns 4 as the size of each element.

## NumPy Array data Attribute


In [120]:
#In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

#In simpler terms, 
#the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

#Let's see an example.

In [121]:
import numpy as np

In [122]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],[6, 7, 8]])
print(array1.data)
print(array2.data)


In [123]:
#Here, the data attribute returns the memory addresses of the data for array1 and array2 respectively.

## NumPy Input Output

In [125]:
#NumPy offers input/output (I/O) functions for loading and saving data to and from files.

#Input/output functions support a variety of file formats, including binary and text formats.

#The binary format is designed for efficient storage and retrieval of large arrays.
#The text format is more human-readable and can be easily edited in a text editor.

## Most Commonly Used I/O Functions


### Function	Description
##### save()	saves an array to a binary file in the NumPy .npy format.
##### load()	loads data from a binary file in the NumPy .npy format
##### savetxt()	saves an array to a text file in a specific format
##### loadtxt()	loads data from a text file.


## NumPy save() Function


#### In NumPy, the save() function is used to save an array to a binary file in the NumPy .npy format.

#Here's the syntax of the save() function,

#np.save(file, array)

In [130]:
#file - specifies the file name (along with path if required)

#array - specifies the NumPy array to be saved

In [131]:
#Now, let's see an example.
 #create a NumPy array
array1 = np.array([[1, 3, 5],  [7, 9, 11]])

# save the array to a file
np.save('file1',array1)
#Here, we saved the NumPy array named array1 to the binary file named file1.npy in our current directory.


## NumPy load() Function


### in the previous example, we saved an array to a binary file. Now we'll load that saved file using the load() function.

In [134]:
#Let's see an example.

# load the saved NumPy array
loaded_array = np.load('file1.npy')
# display the loaded array
print(loaded_array)


[[ 1  3  5]
 [ 7  9 11]]


In [135]:
#Here, we have used the load() function to read a binary file named file1.npy.
#This is the same file we created and saved using save() function in the last example.

## NumPy savetxt() Function


#### In NumPy, we use the savetxt() function to save an array to a text file.

#### Here's the syntax of the savetxt() function:

#np.save(file, array)

In [139]:
#file - specifies the file name
#array - specifies the NumPy array to be saved

In [140]:
#Now, let's see an example,
#create a NumPy array
array2 = np.array([[1, 3, 5],  [7, 9, 11]])
np.savetxt('file2.txt',array2)
#The code above will save the NumPy array array2 to the text file named file2.txt in our current directory.

##### We use the loadtxt() function to load the saved txt file.

##### Let's see an example to load the file2.txt file that we saved earlier.

In [142]:
# load the saved NumPy array
loaded_array = np.loadtxt('file2.txt')
print(loaded_array)

[[ 1.  3.  5.]
 [ 7.  9. 11.]]


##### Here, we have used the loadtxt() function to load the text file named file2.
##### txt that was previously created and saved using the savetxt() function.

##### Note: The values in the loaded array have dots . because loadtxt() reads the values as floating point numbers by default.



## Numpy Array Indexing


#### In NumPy, each element in an array is associated with a number. The number is known as an array index.

#### Let's see an example to demonstrate NumPy array indexing.


In [146]:
#1,3,5,7,9
#0 1 2 3 4.......index  

In [147]:
#In the above array, 5 is the 3rd element. However, its index is 2.

#This is because the array indexing starts from 0, that is, the first element of the array has index 0, the second element has index 1, and so on.

#Now, we'll see how we can access individual items from the array using the index number.

## Access Array Elements Using Index
#We can use indices to access individual elements of a NumPy array.

#Suppose we have a NumPy array:



In [149]:
# array1 = np.array([1, 3, 5, 7, 9])
#Now, we can use the index number to access array elements as:
#array1[0] - to access the first element, i.e. 1
#array1[2] - to access the third element, i.e. 5
#array1[4] - #to access the fifth element, i.e. 9

### Modify Array Elements Using Index


In [151]:
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10])

# change the value of the first element
numbers[0] = 12
print("After modifying first element:",numbers)    

After modifying first element: [12  4  6  8 10]


### NumPy Negative Array Indexing


In [153]:
#NumPy allows negative indexing for its array. The index of -1 refers to the last item, -2 to the second last item and so on.

In [154]:
import numpy as np

# create a numpy array
numbers = np.array([1, 3, 5, 7, 9])

# access the last element
print(numbers[-1])   

numbers[-3] = -1
print("modify number is:",numbers)

9
modify number is: [ 1  3 -1  7  9]


In [167]:
array1 = np.array([[1, 3, 5], [7, 9, 2],[4, 6, 8]])
print(array1[2,1])
print(array1[0,2])
print(array1[1,2])
print(array1[0,1])

6
5
2
3


In [179]:
#create a 2D array 
array2 = np.array([[1, 3, 5],  [7, 9, 2],  [4, 6, 8]])
# access the second row of the array
second_row = array2[1, :]
print("Second Row:", second_row)  


Second Row: [7 9 2]


In [181]:
array2 = np.array([[1, 3, 5],  [7, 9, 2],  [4, 6, 8]])
third_raw = array2[2, :]
print(third_raw)

[4 6 8]


In [185]:
import numpy as np

# create a 3D array with shape (2, 3, 4)
array3 = np.array([[[1, 2, 3, 4],  [5, 6, 7, 8], [9, 10, 11, 12]]   ,   [[13, 14, 15, 16], [17, 18, 19, 20],  [21, 22, 23, 24]]])
# access a specific element of the array
element = array3[1,1,2]
print(element)


19


In [191]:
print(array3[1, :])


[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [193]:
print(array3[:, 1])

[[ 5  6  7  8]
 [17 18 19 20]]


In [199]:
print(array3[ :2: ])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [203]:
array3[1, :] 

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])