In [1]:
import numpy as np

In [3]:
arr1 =np.array([])  # create an empty array

In [4]:
arr1

array([], dtype=float64)

In [5]:
my_list=[1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [11]:
a.ndim

1

In [13]:
a.size

5

In [15]:
a.shape

(5,)

In [17]:
my_matrix = [[1,2,3,4],[5,6,7,8],[5,78,98,78]]

In [19]:
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [5, 78, 98, 78]]

In [21]:
b=np.array(my_matrix)      #gernerate a 2-d array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 5, 78, 98, 78]])

In [23]:
b.ndim

2

In [25]:
b.size

12

In [27]:
b.shape

(3, 4)

In [29]:
type(b)

numpy.ndarray

In [31]:
b.dtype

dtype('int32')

In [33]:
arr2=np.array([[[1,2,5],[5,6,8]],[[6,8,78],[5,89,58]]])
arr2

array([[[ 1,  2,  5],
        [ 5,  6,  8]],

       [[ 6,  8, 78],
        [ 5, 89, 58]]])

In [35]:
arr2.shape

(2, 2, 3)

In [37]:
arr2.size

12

In [39]:
arr2.ndim

3

In [41]:
type(arr2)

numpy.ndarray

In [43]:
arr2.dtype


dtype('int32')

In [45]:
arr3=np.array([[[1,2,5],[5,6,8]],[[6,8,78],[5,89,58]]])
arr2

array([[[ 1,  2,  5],
        [ 5,  6,  8]],

       [[ 6,  8, 78],
        [ 5, 89, 58]]])

In [47]:
arr3=arr2.reshape((1,3,4))
arr3

array([[[ 1,  2,  5,  5],
        [ 6,  8,  6,  8],
        [78,  5, 89, 58]]])

In [49]:
arr3.shape

(1, 3, 4)

In [51]:
arr3

array([[[ 1,  2,  5,  5],
        [ 6,  8,  6,  8],
        [78,  5, 89, 58]]])

In [53]:
# arange

#return evenly spaced values within a given interval

In [55]:
np.arange(15)  #start ,end ,step

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.arange(100,2,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [59]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [61]:
# zeros and ones
# generate arrays of zeros or ones 

In [63]:
np.zeros(3)

array([0., 0., 0.])

In [65]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.ones((4,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

### linspace


In [74]:
np.linspace(1,50,50)   #default 50 observations
                    #both the start and end are included in the array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [76]:
np.linspace(1,25,100)  

array([ 1.        ,  1.24242424,  1.48484848,  1.72727273,  1.96969697,
        2.21212121,  2.45454545,  2.6969697 ,  2.93939394,  3.18181818,
        3.42424242,  3.66666667,  3.90909091,  4.15151515,  4.39393939,
        4.63636364,  4.87878788,  5.12121212,  5.36363636,  5.60606061,
        5.84848485,  6.09090909,  6.33333333,  6.57575758,  6.81818182,
        7.06060606,  7.3030303 ,  7.54545455,  7.78787879,  8.03030303,
        8.27272727,  8.51515152,  8.75757576,  9.        ,  9.24242424,
        9.48484848,  9.72727273,  9.96969697, 10.21212121, 10.45454545,
       10.6969697 , 10.93939394, 11.18181818, 11.42424242, 11.66666667,
       11.90909091, 12.15151515, 12.39393939, 12.63636364, 12.87878788,
       13.12121212, 13.36363636, 13.60606061, 13.84848485, 14.09090909,
       14.33333333, 14.57575758, 14.81818182, 15.06060606, 15.3030303 ,
       15.54545455, 15.78787879, 16.03030303, 16.27272727, 16.51515152,
       16.75757576, 17.        , 17.24242424, 17.48484848, 17.72

In [78]:
np.linspace(0,25,retstep=True)

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

In [80]:
np.linspace(0,200,10)  #defalut retstep = false

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

### eye

In [83]:
# creates an identity matrix

In [85]:
np.eye(5)      #generate 2nd array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
# create am eye from zeros array

### use of copy function

In [90]:
my_list=[5,4,7,2,0,4,7,8.45,45,75,20,10]

In [92]:
arr3=np.array(my_list)
arr3

array([ 5.  ,  4.  ,  7.  ,  2.  ,  0.  ,  4.  ,  7.  ,  8.45, 45.  ,
       75.  , 20.  , 10.  ])

In [94]:
arr3[:10]=30
arr3

array([30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 20., 10.])

In [96]:
arr4=arr3.copy()

In [98]:
arr4[10:]=150
arr4

array([ 30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.,  30., 150.,
       150.])

### rand

In [101]:
# create an array of the given shape and populate it with random samples from a uniform distribution

In [103]:
np.random.rand()

0.4586512651817063

In [105]:
np.random.rand(10)

array([0.72058328, 0.49865262, 0.99570273, 0.28173819, 0.35235887,
       0.12339504, 0.41568576, 0.19119109, 0.43397824, 0.62873196])

In [107]:
np.random.rand(20).reshape((5,4))

array([[0.59399634, 0.64177689, 0.32403192, 0.27592176],
       [0.41626965, 0.27523678, 0.48411453, 0.93324611],
       [0.4000651 , 0.07995861, 0.7273888 , 0.26245912],
       [0.58348317, 0.27010964, 0.19515215, 0.31669159],
       [0.64518749, 0.88556932, 0.51403767, 0.75961204]])

In [109]:
arr1=np.random.randn()
arr1

-1.914916020951998

In [111]:
arr1=np.random.randn(40)
arr1

array([-1.34985861, -0.2701556 , -0.80290805, -2.42935266,  0.5513744 ,
        0.15083898,  0.04627157,  0.255559  ,  1.31759405, -2.7823448 ,
       -1.21862707, -2.50598673,  0.77464512,  0.51328437,  0.25303533,
       -0.5201988 ,  1.26650533,  0.02743006, -1.20950885,  1.33738794,
        0.52920543, -0.9846332 ,  0.86413388,  0.55894535, -0.55469254,
       -1.00682251,  0.07648392,  0.48870486, -0.93130508, -0.90094956,
       -2.67953465,  1.14478585, -0.85000341, -0.5033171 , -1.10076158,
        1.18405014,  1.3646811 ,  1.40984437,  1.17490976, -1.42762977])

### rabdint

In [114]:
np.random.randint(1,50)

49

In [116]:
np.random.randint(1,100,10)

array([11, 23, 24, 16, 44, 82, 15,  6,  2, 82])

In [118]:
np.random.randint(1,60,50)

array([ 5, 29,  4, 12, 40, 56, 21, 11,  1,  6, 20,  2, 58, 21,  6, 15, 54,
       28, 41, 48, 27, 22,  3, 11, 57, 58, 58,  8, 57,  2,  1, 43, 15, 36,
        3, 36, 59, 57, 44, 43, 43,  8, 28, 27,  8, 14, 49, 54, 30, 19])

In [120]:
np.random.randint(1,3,10)

array([1, 2, 1, 1, 1, 1, 2, 1, 1, 2])

In [12]:
import numpy as np

In [14]:
c = np.array([5,4,5,2,0,4,7,8,4,75,20,10])
c


array([ 5,  4,  5,  2,  0,  4,  7,  8,  4, 75, 20, 10])