### Insert the correct argument for creating a NumPy array with 2 dimensions.

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5],ndmin=2)
arr

array([[1, 2, 3, 4, 5]])

### Insert the correct syntax for checking the number of dimension of a NumPy array.


In [5]:
arr = np.array([1, 2, 3, 4])
print(arr.ndim)

1


In [6]:
arr1 = np.array([[[1,2,2]],[[3,4,5]]])
print(arr1.ndim)

3


### Insert the correct syntax for printing the first item in the array.



In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


### Insert the correct syntax for printing the number 50 from the array.



In [10]:
arr = np.array([10,20,30,40,50,60])
print(arr[4])

50


### Insert the correct syntax for printing the number 50 from the array.


In [12]:
arr = np.array([[10,20,30,40,50,60],[40,10,20,50,30,50]])

In [13]:
print(arr[1,3])

50


### Use negative index to print the last item in the array.


In [15]:
arr3 = np.array([10, 20, 30, 40, 50])
print(arr3[-1])

50


### Insert the correct slicing syntax to print the following selection of the array:

### Everything from (including) the second item to (not including) the fifth item.



In [17]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr

array([10, 15, 20, 25, 30, 35, 40])

In [18]:
print(arr[1:4])

[15 20 25]


In [19]:
Everything from (including) the third item to (not including) the fifth item.


SyntaxError: invalid syntax (2337716687.py, line 1)

In [ ]:
print(arr[2:4])

### Insert the correct slicing syntax to print the following selection of the array:
### Every other item from (including) the second item to (not including) the fifth item.

In [ ]:
arr5 = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr5[1:4:2])

### Insert the correct slicing syntax to print the following selection of the array:
### Every other item from the entire array.
### use the step syntax.




In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[::2])

In [ ]:
print(arr[::1])

In [ ]:
print(arr[::-1])

In [ ]:
print(arr[1::])

In [ ]:
print(arr[0::])

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


### NumPy uses a character to represent each of the following data types, which one?
#i = integer

#b = boolean

#u = unsigned integer

#f = float

#c = complex float

#m = timedelta

#M = datetime

#O = object

#S = string

### slicing of numpy arrays

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])

In [ ]:
print(arr[::1])

In [ ]:
print(arr[::2])

### slicing in 2d array

In [ ]:
a = np.array([[120,24,85,52],[854,652,3,85]])
print(a[1,1:3])

In [ ]:
print(a[0,1:3])

### checking the data type of an array

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

In [ ]:
arr = np.array(['animals','bat','cat'])
print(arr.dtype)

### create an array with data types 4 bytes integer 

In [34]:
import numpy as np

In [39]:
arr = np.array ([1,2,3,4],dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### numpy array shape 

### print the shape of a 2d array

In [47]:
arr = np.array([[1,5,5,6],[68,5,2,5]])
print(arr.shape)
            

(2, 4)


In [54]:
arr1 = np.array([[[1,5,5,6],[5,5,6,5],[68,5,2,5]]])
print(arr1.shape)

(1, 3, 4)
