## NumPy Array Reshaping

#### NumPy array reshaping simply means changing the shape of an array without changing its data.

##### Let's say we have a 1D array.

In [7]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array 
# with 2 rows and 4 columns
result = np.reshape(array1,(2,4))
print(result)

[[1 3 5 7]
 [2 4 6 8]]


## NumPy Arithmetic Array Operations


In [12]:
#Element-wise Operation		
#Addition	        +	             add()
#Subtraction       	-	             subtract()
#Multiplication	    *	             multiply()
#Division	        /	             divide()
#Exponentiation	    **	             power()
#Modulus         	%	             mod()


In [16]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition
sum_array = array1 + array2
print("Sum:", sum_array)

# Element-wise multiplication
product_array = array1 * array2
print("Product:", product_array)

Sum: [5 7 9]
Product: [ 4 10 18]


In [18]:
# Create a 1D array
array = np.arange(12)

# Reshape the array to 3x4
reshaped_array = array.reshape(3, 4)
print("Reshaped Array:", reshaped_array)

Reshaped Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
# Create an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate mean, median, and standard deviation
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [22]:
# Create two arrays
array1 = np.array([10, 20, 30, 40])
array2 = np.array([15, 25, 35, 30])

# Element-wise comparison
comparison = array1 > array2
print("Comparison (array1 > array2):", comparison)

Comparison (array1 > array2): [False False False  True]


In [26]:
# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
product_matrix = np.dot(matrix1, matrix2)
print("Matrix Product:", product_matrix)


Matrix Product: [[19 22]
 [43 50]]


In [28]:
# Create a 3x3 array
array = np.arange(9).reshape(3, 3)

# Slice the array
sliced_array = array[1:, 1:]
print("Sliced Array:\n", sliced_array)

# Indexing
indexed_element = array[1, 2]
print("Indexed Element:", indexed_element)

Sliced Array:
 [[4 5]
 [7 8]]
Indexed Element: 5
