### arange

### Return evenly spaced values within a given interval.

In [ ]:
#np.arange(start,end,step)

In [37]:
np.arange(15) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
np.arange(1,5)

array([1, 2, 3, 4])

In [49]:
np.arange(100,2,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

## joining numpy arrays 

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 5 6 7]


In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])
arr = np.sum((arr1,arr2))
print(arr)

24


### join 2d array

In [6]:
arr1 = np.array([[1,2,3],[8,6,3]])
arr2 = np.array([[5,6,7],[5,7,4]])
arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)


[[1 2 3 5 6 7]
 [8 6 3 5 7 4]]


In [7]:
arr1 = np.array([[1,2,3],[8,6,3]])
arr2 = np.array([[5,6,7],[5,7,4]])
arr = np.concatenate((arr1,arr2),axis = 0)
print(arr)


[[1 2 3]
 [8 6 3]
 [5 6 7]
 [5 7 4]]


### spliting numpy arrays

### splitting the array in 4 parts

In [10]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = np.array_split(arr,4)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


### splitting the array in 2 parts

In [12]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = np.array_split(arr,2)
print(new_arr)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


## Data Types in NumPy
#### NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

##### Below is a list of all data types in NumPy and the characters used to represent them.

#i - integer

#b - boolean

#u - unsigned integer

#f - float

#c - complex float

#m - timedelta

#M - datetime

#O - object

#S - string

#U - unicode string

#V - fixed chunk of memory for other type ( void )

### `Get the data type of an array object:

In [15]:
import numpy as np

In [16]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


### Get the data type of an array containing strings:

In [18]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


### Create an array with data type string:

In [20]:
arr = np.array([1, 2, 3, 4],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


#### Create an array with data type 4 bytes integer:

In [22]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### A non integer string like 'a' can not be converted to integer (will raise an error):

In [24]:
arr = np.array(['a', '2', '3'], dtype='i4')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

### Change data type from float to integer by using 'i' as parameter value:

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
arr1 = arr.astype('i')
print(arr1)
print(arr1.dtype)

### Change data type from float to integer by using int as parameter value:

In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

### Change data type from integer to boolean:

In [ ]:
arr = np.array([1, 0, 3])
arr1 =arr.astype(bool)
print(arr)
print(arr1)

In [ ]:
arr = np.array([-1, 0, 1])
newarr = arr.astype('S')
print(newarr)

### COPY:

#### Make a copy, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() 
arr[0] = 42   
print(x)     #The copy SHOULD NOT be affected by the changes made to the original array.
                  

In [ ]:
print(arr)

### Make a view, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 40
print(arr)
print(x)   #The view SHOULD be affected by the changes made to the original array.

In [ ]:
#Check if Array Owns its Data
#As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

#Every NumPy array has the attribute base that returns None if the array owns the data.

#Otherwise, the base  attribute refers to the original object.

### Print the value of the base attribute to check if an array owns it's data or not:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

a = arr.copy()
b = arr.view()

print(a.base)
print(b.base)

In [ ]:
original_array = np.array([1, 2, 3])
x = original_array.copy()               
x[1] = 5
print(original_array) #The copy SHOULD NOT be affected by the changes made to the original array.

In [ ]:
original_array = np.array([4,5,6])
x= original_array.view()
x[0] = 1
print(original_array)  #The view SHOULD be affected by the changes made to the original array.  


## Shape of an Array
### The shape of an array is the number of elements in each dimension.

#### NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

### Print the shape of a 2-D array:

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

## Reshaping arrays
#### Reshaping means changing the shape of an array.

#### The shape of an array is the number of elements in each dimension.

#### By reshaping we can add or remove dimensions or change number of elements in each dimension.



## Convert the following 1-D array with 12 elements into a 2-D array.

## The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arrnew = arr.reshape(3,4)
print(arrnew)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr1 = arr.reshape(2,3,2)
print(arr1)

### Can We Reshape Into any Shape?

### We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

## Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

## Check if the returned array is a copy or a view:


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2,4).base)      
print("The example above returns the original array, so it is a view.")

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = arr.copy()
arr[0] = 5
print(arr.reshape(4,2).base)  

## ravel & flatten

#### converts multidimensional array into 1d array 

In [ ]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[7,4,1]]])
print(a)
print("dimension is",a.ndim)

b = a.ravel()
print(b)
print("the new dimension is",b.ndim)


In [ ]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[7,4,1]])

In [ ]:
print(c)
print("dimension is",c.ndim)

d = c.flatten()
print(d)
print("the new dimension is",d.ndim)

### Unique Function

In [ ]:
k = np.array([1,2,5,7,8,8,8,5,6,7,3,0,4,5,10])
print(k)
inique = np.unique(k)
print(inique)

In [ ]:
k = np.array([1,2,5,7,8,8,8,5,6,7,3,0,4,5,10])
print(k)
x = np.unique(k,return_index = True) ## use for index position
print(x)

In [ ]:
k = np.array([1,2,5,7,8,8,8,5,6,7,3,0,4,5,10])
print(k)
x = np.unique(k,return_index = True) ## use for index position
print(x)

In [ ]:
k = np.array([1,2,5,7,8,8,8,5,6,7,3,0,4,5,10])
print(k)
x = np.unique(k,return_index = True,return_counts = True) ## use for repeted values count
print(x)

### Delete

In [ ]:
a = np.array([45,63,2,8])
del1 = np.delete(a,[0])
print(del1)

In [62]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[7,4,1]]])
print(b)
x = np.delete(b,1,axis =0)
print()
print(x)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [7 4 1]]]

[[[1 2 3]
  [4 5 6]]]
